const grid=document.querySelector('#work-grid');
function render(filter='all'){
 if(!grid)return;
 grid.innerHTML=works.map((w,i)=>filter!=='all'&&w.cat!==filter?'':`<button class="work-card" data-case="${i}" aria-label="查看${w.title}"><div class="work-media"><img loading="lazy" src="${w.poster}" alt="${w.title}">${w.video?`<video muted loop playsinline preload="none" poster="${w.poster}" src="${w.video}"></video>`:''}<span class="view">${w.video?'播放作品':'查看作品'} ↗</span></div><div class="work-label"><div><small>0${i+1} / ${w.cat==='video'?'MOTION & COMMERCIAL':'VISUAL & WORKFLOW'}</small><h3>${w.title}</h3></div><span>↗</span></div></button>`).join('');
 grid.querySelectorAll('.work-card').forEach(card=>{let v=card.querySelector('video');card.addEventListener('mouseenter',()=>{if(v&&!matchMedia('(prefers-reduced-motion: reduce)').matches)v.play().catch(()=>{})});card.addEventListener('mouseleave',()=>{if(v)v.pause()})});
}
render();
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filters .active')?.classList.remove('active');b.classList.add('active');render(b.dataset.filter)}));
const stages=[['产品理解','梳理产品卖点、目标人群和使用场景，为商业视觉与广告创意确定表达重点。'],['创意分镜','拆解钩子、镜头节奏与产品介入方式，把创意转换为可执行的画面任务。'],['AI生成','围绕产品辨识点与画面风格组织参考和提示词，控制同一作品中的产品、人物与场景一致性。'],['成片交付','完成剪辑、字幕、视觉包装与版本输出，并将高频操作沉淀为可复用的SOP。']];
function stage(i){if(!document.querySelector('#stage-detail'))return;document.querySelector('#stage-detail').innerHTML=`<h3>${stages[i][0]}</h3><p>${stages[i][1]}</p>`}stage(0);
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.pipeline .active')?.classList.remove('active');b.classList.add('active');stage(+b.dataset.stage)}));
const dialog=document.querySelector('dialog');
document.addEventListener('click',e=>{const c=e.target.closest('[data-case]');if(!c)return;e.preventDefault();let i=+c.dataset.case,w=works[i];document.querySelector('#case-body').innerHTML=`<p class="eyebrow">SELECTED CASE / 0${i+1}</p><h2>${w.title}</h2><p class="case-desc">${w.desc}</p>${w.video?`<video class="case-video" controls playsinline preload="metadata" poster="${w.poster}" src="${w.video}"></video>`:`<div class="case-images">${w.images.map(src=>`<img src="${src}" alt="详情页视觉作品">`).join('')}</div>`}<div class="case-info"><article><h3>${i===0?'个人贡献':'展示重点'}</h3><p>${i===0?'原作品集记录：主导制作该跨境电商广告视频，并围绕同一素材方向进行裂变迭代。':'该作品展示的能力与内容以当前成片和原作品集描述为依据。具体职责与制作过程将在补充项目材料后完善。'}</p></article><article><h3>${i===0?'成果与来源':'制作过程'}</h3><p>${i===0?'800w+播放、1.6w+点赞、约40w美金关联销售额；原作品集另记录视频组周期销售额约100w美金。统计周期、投放归因及证明材料待补充。':'后续可加入产品参考、脚本分镜、AI生成画面与后期对照；当前展示真实已有作品。'}</p>${i===0?'<a class="text-link" href="https://www.facebook.com/100068731095744/posts/1209473628020329/" target="_blank" rel="noreferrer">查看Facebook原案例 ↗</a>':''}</article></div>`;document.querySelectorAll('video').forEach(v=>v.pause());dialog.showModal();document.body.style.overflow='hidden'});
function close(){dialog.close();document.body.style.overflow='';dialog.querySelectorAll('video').forEach(v=>v.pause())}document.querySelector('.close').onclick=close;dialog.addEventListener('click',e=>{if(e.target===dialog){let r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';dialog.querySelectorAll('video').forEach(v=>v.pause())});
let hero=document.querySelector('.hero-art video');if(hero)document.querySelector('#hero-toggle').onclick=function(){if(hero.paused){hero.play().catch(()=>{});this.textContent='暂停 Ⅱ'}else{hero.pause();this.textContent='播放 ▶'}};if(hero&&matchMedia('(prefers-reduced-motion: reduce)').matches){hero.autoplay=false;hero.pause();document.querySelector('#hero-toggle').textContent='播放 ▶'}
