(()=>{const projects={
 museframe:{mark:'MF',name:'MuseFrame',sub:'IMAGE & VIDEO STUDIO',url:'https://museframe-image-generator.onrender.com/',role:'独立搭建网页工作台',contribution:'通过AI辅助开发，整合生成入口、参数配置、会话结果与作品库，并接入 Grsai API。',views:[['overview','01 新版创作概览','从灵感到成片，一个创作空间。','重设计版以创作概览为入口，集中展示生图、生视频、作品库和API连接配置。',['统一的创作入口','创作统计与最近作品','图片、视频与灵感管理']],['image','02 生图工作台','从提示词到商品视觉。','新版深色创作界面，将模型选择、参考输入、输出配置与结果预览集中到同一个空间。',['文生图 / 图生图切换','模型、比例、规格与张数配置','生成结果与提示词记录']],['video','03 生视频工作台','从画面设定到动态素材。','配置生成方式、比例、清晰度与时长，衔接异步任务和资产管理。',['文生视频 / 图生视频入口','首帧、尾帧与多图参考入口','生成任务与作品记录']],['library','04 作品库','生成之后，继续管理作品。','集中查看图片、视频与进行中的任务，通过类型和来源筛选整理资产。',['图片 / 视频类型筛选','文生 / 图生来源筛选','同一API Key同步服务端记录']]],evidence:[['创作入口','围绕制作组织功能','图片与视频沿用统一的操作结构，降低重复配置成本。'],['参数控制','让生成规格可以控制','模型、比例、清晰度与时长对应不同素材需求。'],['资产管理','衔接生成与后期交付','将任务状态、作品筛选与下载入口纳入制作链路。']]},
 zhixu:{mark:'知',name:'知序 · 企业知识助手',sub:'KNOWLEDGE → ACTION',url:'https://name-enterprise-rag-assistant.onrender.com/rag_ui.html',role:'搭建知识检索与问答工作台',contribution:'通过AI辅助开发构建问答界面与知识检索流程，整理跨境运营资料、诊断问答及官方来源，支持引用查看与建议导出。',views:[['ask','01 问助手','把业务问题，变成下一步行动。','围绕运营诊断、素材改法、落地页优化、客服回复和老板汇报组织提问入口，回答与参考资料并列呈现。',['按场景选择工作模式','多轮追问与资料引用','复制与Markdown导出']],['knowledge','02 知识库','让每个回答，都有依据。','44份文档、253个知识片段，覆盖20个运营主题、100个诊断问答，并登记30个官方来源。',['按主题与名称搜索资料','查看知识文档及分类','下载运营知识包']],['history','03 历史问答','让每次思考，都有迹可循。','保存问题、回答与资料引用，支持重新打开与继续追问。历史存储在当前浏览器，可通过备份迁移。',['搜索历史问题','导出备份 / 导入记录','重新打开建议与引用']]],evidence:[['业务场景','让提问更具体','按运营、素材、客服等角色配置入口，强调数据和问题背景。'],['知识依据','让建议可以追溯','知识检索与参考资料并列展示，便于核对回答依据。'],['持续使用','让思考能够积累','历史问答、草稿与导出入口衔接后续协作。']]}
};
let activeProject='museframe';const $=s=>document.querySelector(s),dialog=$('#mf-dialog');
function selectView(index){const p=projects[activeProject],v=p.views[index];document.querySelectorAll('[data-view]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1});const src=activeProject+'/'+v[0]+'.png';$('#mf-image').src=src;$('#mf-image').alt=p.name+' - '+v[1]+'本地界面';$('#mf-large').src=src;$('#mf-large').alt=$('#mf-image').alt;$('#mf-title').textContent=v[2];$('#mf-description').textContent=v[3];$('#mf-points').replaceChildren(...v[4].map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('.mf-shot').scrollTop=0;$('#project-caption').textContent=p.name+(v[0]==='overview'?' / 重设计版概览':' / 本地功能界面');$('.mf-story small').textContent=v[0]==='overview'?'用户提供的重设计版截图。点击标签查看其他功能界面，点击放大查看细节。':'采集自本地功能版本，尚未连接模型接口；各功能截图与重设计版概览的版本不同。'}
function selectProject(key){activeProject=key;const p=projects[key];document.querySelectorAll('[data-project]').forEach(b=>{const selected=b.dataset.project===key;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;if(selected)$('#project-panel').setAttribute('aria-labelledby',b.id)});$('#project-mark').textContent=p.mark;$('#project-name').textContent=p.name;$('#project-subtitle').textContent=p.sub;$('#project-link').href=p.url;$('#project-caption').textContent=p.name+' / 最新本地界面';$('#project-role').textContent=p.role;$('#project-contribution').textContent=p.contribution;$('#view-tabs').setAttribute('aria-label',p.name+'功能界面');$('#view-tabs').replaceChildren(...p.views.map((v,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('role','tab');b.dataset.view=i;b.textContent=v[1];b.onclick=()=>selectView(i);return b}));$('#project-evidence').replaceChildren(...p.evidence.map((e,i)=>{const a=document.createElement('article'),span=document.createElement('span'),h=document.createElement('h3'),d=document.createElement('p');span.textContent='0'+(i+1)+' / '+e[0];h.textContent=e[1];d.textContent=e[2];a.append(span,h,d);return a}));selectView(0)}
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>selectProject(b.dataset.project));document.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;const tabs=[...list.querySelectorAll('[role=tab]')];let i=tabs.indexOf(document.activeElement);if(i<0)return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[i].click();tabs[i].focus()}));$('#mf-zoom').onclick=()=>dialog.showModal();$('.mf-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});selectProject('museframe');
})();
